/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;


import controle.ConexaoBD;
import javax.swing.JOptionPane;
import modelo.modeloCliente;
import modelo.modeloFuncionario;
import modelo.modeloPessoa;


/**
 *
 * @author CASA
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormFuncionario
     */
    public FormCliente() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabelDataDeNascimento = new javax.swing.JLabel();
        campoDataDeNascimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        CadastroDeFuncionario = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoOrgao = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        campoCEP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoUF = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoComplemento = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNome.setText("NOME");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(30, 90, 50, 20);

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome);
        campoNome.setBounds(80, 90, 300, 20);

        jLabelDataDeNascimento.setText("DATA DE NASCIMENTO");
        getContentPane().add(jLabelDataDeNascimento);
        jLabelDataDeNascimento.setBounds(400, 90, 120, 20);

        campoDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataDeNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(campoDataDeNascimento);
        campoDataDeNascimento.setBounds(530, 90, 110, 20);

        jLabel1.setText("RG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 130, 20, 20);

        campoRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRGActionPerformed(evt);
            }
        });
        getContentPane().add(campoRG);
        campoRG.setBounds(80, 130, 140, 20);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(90, 430, 130, 23);

        CadastroDeFuncionario.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        CadastroDeFuncionario.setText("Cadastro de Cliente");
        getContentPane().add(CadastroDeFuncionario);
        CadastroDeFuncionario.setBounds(170, 20, 350, 43);

        jButtonCancelar.setText("Voltar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(450, 430, 130, 23);

        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 130, 34, 20);

        jLabel3.setText("ORGÂO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 130, 40, 20);

        campoOrgao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOrgaoActionPerformed(evt);
            }
        });
        getContentPane().add(campoOrgao);
        campoOrgao.setBounds(290, 130, 90, 20);
        getContentPane().add(campoCPF);
        campoCPF.setBounds(450, 130, 190, 20);
        getContentPane().add(campoCEP);
        campoCEP.setBounds(80, 200, 140, 20);

        jLabel4.setText("CEP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 30, 14);

        jLabel5.setText("UF");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 200, 40, 20);

        campoUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE", "RJ", "PS", "PR" }));
        campoUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUFActionPerformed(evt);
            }
        });
        getContentPane().add(campoUF);
        campoUF.setBounds(280, 200, 90, 20);

        jLabel6.setText("CIDADE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 200, 40, 14);

        campoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(campoCidade);
        campoCidade.setBounds(430, 200, 210, 20);

        jLabel7.setText("BAIRRO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 240, 40, 14);
        getContentPane().add(campoBairro);
        campoBairro.setBounds(80, 240, 190, 20);

        jLabel8.setText("RUA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 240, 21, 14);
        getContentPane().add(campoRua);
        campoRua.setBounds(310, 240, 330, 20);

        jLabel9.setText("E-MAIL");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 170, 34, 14);
        getContentPane().add(campoNumero);
        campoNumero.setBounds(80, 280, 120, 20);

        jLabel10.setText("NÚMERO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 280, 43, 14);

        jLabel11.setText("COMPLEMENTO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 280, 80, 20);
        getContentPane().add(campoComplemento);
        campoComplemento.setBounds(370, 280, 270, 20);
        getContentPane().add(campoEmail);
        campoEmail.setBounds(80, 170, 260, 20);

        jLabel12.setText("TELEFONE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 170, 60, 14);
        getContentPane().add(campoTelefone);
        campoTelefone.setBounds(430, 170, 210, 20);

        setBounds(0, 0, 685, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void campoDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataDeNascimentoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try{
          
            String nome = campoNome.getText();
            String datadenascimento = campoDataDeNascimento.getText();
            String rg = campoRG.getText();
            String orgao = campoOrgao.getText();
            String cpf = campoCPF.getText();
            String email = campoEmail.getText();
            String telefone = campoTelefone.getText();
            String cep = campoCEP.getText();
            String cidade = campoCidade.getText();
            String bairro = campoBairro.getText();
            String rua = campoRua.getText();
            String numero = campoNumero.getText();
            String complemento = campoComplemento.getText(); 
            String uf = campoUF.getSelectedItem().toString();
            
            modeloCliente cliente = new modeloCliente(nome, datadenascimento, rg, orgao, cpf, email, telefone, cep, uf, cidade, bairro, rua, numero, complemento);
            ConexaoBD conecta_funcionario = new ConexaoBD();
            conecta_funcionario.CadastrarCliente(cliente);
            JOptionPane.showMessageDialog(null, "Dados gravados com sucesso!", "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
           
            campoNome.setText("");
            campoDataDeNascimento.setText("");
            campoRG.setText("");
            campoOrgao.setText("");
            campoCPF.setText("");
            campoEmail.setText("");
            campoTelefone.setText("");
            campoCEP.setText("");
            campoCidade.setText("");
            campoBairro.setText("");
            campoRua.setText("");
            campoNumero.setText("");
            campoComplemento.setText("");

        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Erro no banco de dados!"+ex.getMessage(),"Aviso",
	    JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
      tela.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void campoRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRGActionPerformed

    private void campoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCidadeActionPerformed

    private void campoUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUFActionPerformed

    private void campoOrgaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOrgaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOrgaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastroDeFuncionario;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCEP;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoDataDeNascimento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoOrgao;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoRua;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> campoUF;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDataDeNascimento;
    private javax.swing.JLabel jLabelNome;
    // End of variables declaration//GEN-END:variables
}
