/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import visão.FormCliente;
import controle.ConexaoBD;
import javax.swing.JFrame;

/**
 *
 * @author CASA
 */
public class TelaPrincipal extends javax.swing.JFrame {
    ConexaoBD conecta  = new ConexaoBD();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButtonCadFuncionario = new javax.swing.JButton();
        jButtonCadCliente = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jButtonPesFuncionario = new javax.swing.JButton();
        jButtonPesCliente = new javax.swing.JButton();
        jLabelBemVindo = new javax.swing.JLabel();
        jLabelCadastro = new javax.swing.JLabel();
        jLabelPesquisar = new javax.swing.JLabel();
        jLabelmoldurapes = new javax.swing.JLabel();
        jLabelmolduracad = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItemCadUsuario = new javax.swing.JMenuItem();
        jMenuPesquisa = new javax.swing.JMenu();
        jMenuItemPesFuncionario = new javax.swing.JMenuItem();
        jMenuItemPesCliente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario-iloveimg-resized.png"))); // NOI18N
        jButtonCadFuncionario.setToolTipText("Cadastro de Funcionário");
        jButtonCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadFuncionario);
        jButtonCadFuncionario.setBounds(160, 90, 60, 70);

        jButtonCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente-iloveimg-resized.png"))); // NOI18N
        jButtonCadCliente.setToolTipText("Cadrastro de Clientes");
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadCliente);
        jButtonCadCliente.setBounds(240, 90, 60, 70);

        jButtonRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio-iloveimg-resized.png"))); // NOI18N
        jButtonRelatorio.setToolTipText("Relatório dos cadastros");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorio);
        jButtonRelatorio.setBounds(270, 240, 60, 70);

        jButtonPesFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario-iloveimg-resized.png"))); // NOI18N
        jButtonPesFuncionario.setToolTipText("Cadastro de Funcionário");
        jButtonPesFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesFuncionario);
        jButtonPesFuncionario.setBounds(130, 240, 60, 70);

        jButtonPesCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente-iloveimg-resized.png"))); // NOI18N
        jButtonPesCliente.setToolTipText("Cadrastro de Clientes");
        jButtonPesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesCliente);
        jButtonPesCliente.setBounds(200, 240, 60, 70);

        jLabelBemVindo.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(0, 0, 204));
        jLabelBemVindo.setText("Bem-Vindo");
        getContentPane().add(jLabelBemVindo);
        jLabelBemVindo.setBounds(180, 0, 130, 40);

        jLabelCadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCadastro.setText("Cadastro");
        getContentPane().add(jLabelCadastro);
        jLabelCadastro.setBounds(200, 60, 60, 20);

        jLabelPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPesquisar.setText("Pesquisar e Atualizar");
        getContentPane().add(jLabelPesquisar);
        jLabelPesquisar.setBounds(170, 210, 140, 20);

        jLabelmoldurapes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelmoldurapes);
        jLabelmoldurapes.setBounds(120, 200, 220, 130);

        jLabelmolduracad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelmolduracad);
        jLabelmolduracad.setBounds(140, 50, 180, 130);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 490, 340);

        jMenuCadastro.setText("Cadastrar");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jMenuItemCadFuncionario.setText("Funcionários");
        jMenuItemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadFuncionario);

        jMenuItemCadCliente.setText("Clientes");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadCliente);

        jMenuItemCadUsuario.setText("Usuários");
        jMenuCadastro.add(jMenuItemCadUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuPesquisa.setText("Pesquisar e Atualizar");

        jMenuItemPesFuncionario.setText("Funcionário");
        jMenuItemPesFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesFuncionarioActionPerformed(evt);
            }
        });
        jMenuPesquisa.add(jMenuItemPesFuncionario);

        jMenuItemPesCliente.setText("Cliente");
        jMenuItemPesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesClienteActionPerformed(evt);
            }
        });
        jMenuPesquisa.add(jMenuItemPesCliente);

        jMenu1.setText("Relatório");

        jMenuItem1.setText("Funcionário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuPesquisa.add(jMenu1);

        jMenuBar1.add(jMenuPesquisa);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.setToolTipText("Sair do Sistema");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(505, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jButtonCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadFuncionarioActionPerformed
       FormFuncionario formfuncionario = new FormFuncionario();
        formfuncionario.setVisible(true);
    }//GEN-LAST:event_jButtonCadFuncionarioActionPerformed

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        FormCliente formcliente = new FormCliente();
        formcliente.setVisible(true);
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        JFrame frame = new JFrame();
                frame.setContentPane(new RelatorioFuncionario());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jButtonPesFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesFuncionarioActionPerformed
        TelaPesFuncionario telapesfuncionario = new TelaPesFuncionario();
        telapesfuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPesFuncionarioActionPerformed

    private void jButtonPesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesClienteActionPerformed
       TelaPesCliente telapescliente = new TelaPesCliente();
       telapescliente.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonPesClienteActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jMenuItemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionarioActionPerformed
      FormFuncionario formfuncionario = new FormFuncionario();
        formfuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCadFuncionarioActionPerformed

    private void jMenuItemPesFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesFuncionarioActionPerformed
        TelaPesFuncionario telapesfuncionario = new TelaPesFuncionario();
        telapesfuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemPesFuncionarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFrame frame = new JFrame();
                frame.setContentPane(new RelatorioFuncionario());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemPesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesClienteActionPerformed
       TelaPesCliente telapescliente = new TelaPesCliente();
       telapescliente.setVisible(true);
       dispose();
    }//GEN-LAST:event_jMenuItemPesClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonCadFuncionario;
    private javax.swing.JButton jButtonPesCliente;
    private javax.swing.JButton jButtonPesFuncionario;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelmolduracad;
    private javax.swing.JLabel jLabelmoldurapes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadFuncionario;
    private javax.swing.JMenuItem jMenuItemCadUsuario;
    private javax.swing.JMenuItem jMenuItemPesCliente;
    private javax.swing.JMenuItem jMenuItemPesFuncionario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuPesquisa;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
